fix: build config

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,21 +1,46 @@
 ngx_addon_name=ngx_http_proxy_request_cookies_control_module
 
-if [ "$NGX_HTTP_PROXY_FILTER" != YES ]; then
-    echo "$0: error: ngx_http_proxy_request_cookies_control_module requires ngx_http_proxy_filter_module"
+if [ "$HTTP" = NO ]; then
+    echo "$0: error: ngx_http_proxy_request_cookies_control_module requires HTTP"
     exit 1
 fi
 
-PROXY_REQUEST_COOKIES_CONTROL_INCS="$ngx_addon_dir/../ngx_http_proxy_filter_module"
+if [ "$HTTP_PROXY" != YES ]; then
+    echo "$0: error: ngx_http_proxy_request_cookies_control_module requires HTTP proxy"
+    exit 1
+fi
 
-if [ $ngx_module_link = DYNAMIC ]; then
+if [ "$ngx_module_link" = DYNAMIC ]; then
+    echo "$0: error: ngx_http_proxy_request_cookies_control_module must be built with --add-module"
+    exit 1
+fi
+
+if test ! -f "$NGX_AUTO_CONFIG_H"                                         \
+    || ! grep -q "NGX_HTTP_PROXY_FILTER" "$NGX_AUTO_CONFIG_H"
+then
+    echo "$0: error: ngx_http_proxy_request_cookies_control_module requires ngx_http_proxy_filter_module"
+    echo "$0: error: add ngx_http_proxy_filter_module before ngx_http_proxy_request_cookies_control_module"
+    exit 1
+fi
+
+PROXY_REQUEST_COOKIES_CONTROL_INCS="$ngx_addon_dir"
+
+PROXY_REQUEST_COOKIES_CONTROL_SRCS="$ngx_addon_dir/ngx_http_proxy_request_cookies_control_module.c"
+
+PROXY_REQUEST_COOKIES_CONTROL_DEPS=
+
+if test -n "$ngx_module_link"; then
     ngx_module_type=HTTP
-    ngx_module_name=ngx_http_proxy_request_cookies_control_module
+    ngx_module_name="$ngx_addon_name"
     ngx_module_incs="$PROXY_REQUEST_COOKIES_CONTROL_INCS"
-    ngx_module_srcs="$ngx_addon_dir/ngx_http_proxy_request_cookies_control_module.c"
+    ngx_module_deps="$PROXY_REQUEST_COOKIES_CONTROL_DEPS"
+    ngx_module_srcs="$PROXY_REQUEST_COOKIES_CONTROL_SRCS"
+    ngx_module_libs=
 
     . auto/module
 else
-    HTTP_MODULES="$HTTP_MODULES ngx_http_proxy_request_cookies_control_module"
+    HTTP_MODULES="$HTTP_MODULES $ngx_addon_name"
     HTTP_INCS="$HTTP_INCS $PROXY_REQUEST_COOKIES_CONTROL_INCS"
-    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_proxy_request_cookies_control_module.c"
+    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $PROXY_REQUEST_COOKIES_CONTROL_SRCS"
+    NGX_ADDON_DEPS="$NGX_ADDON_DEPS $PROXY_REQUEST_COOKIES_CONTROL_DEPS"
 fi
